runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD:  # TODO: '<password>'
  INSTANCE_CONNECTION_NAME: #TODO: '<instance_identifier>'

beta_settings:
  cloud_sql_instances: #TODO: '<instance_identifier>'
